services:
    frontend:
        image: portfolio-frontend:1.0
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
            target: production
        # 1. Define where the command runs
        working_dir: /portfolio
        env_file:
            - .env
        ports:
            - "3000:3000"
